package edge

import (
	"fmt"
	"net/url"
	"strconv"
	"strings"
)

const openShellBinaryPath = "/app/alice-bin"

type openShellEndpoint struct {
	host string
	port int
}

// GenerateOpenShellPolicy generates an OpenShell sandbox policy YAML from the
// given Config. Only enabled connectors produce network_policies blocks;
// disabled connectors are omitted entirely. The static filesystem and process
// sections are always emitted unchanged.
//
// The output is ready to write to a file and apply with:
//
//	openshell policy set <sandbox-name> --policy <file> --wait
func GenerateOpenShellPolicy(cfg Config) string {
	var b strings.Builder

	b.WriteString("# OpenShell sandbox policy generated by the Alice edge agent.\n")
	b.WriteString("# Generated with: edge-agent -config <path> -generate-openshell-policy\n")
	b.WriteString("#\n")
	b.WriteString("# Apply with:\n")
	b.WriteString("#   openshell policy set edge-agent \\\n")
	b.WriteString("#     --policy <this-file> \\\n")
	b.WriteString("#     --wait\n")
	b.WriteString("#\n")
	b.WriteString("# Network entries are dynamic (hot-reloadable on a running sandbox).\n")
	b.WriteString("# Filesystem and process entries are static (locked at sandbox creation).\n")
	b.WriteString("# See docs/openshell.md for the full setup guide.\n")
	b.WriteString("\n")
	b.WriteString("version: 1\n")
	b.WriteString("\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# Filesystem (static - locked at sandbox creation)\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("filesystem_policy:\n")
	b.WriteString("  include_workdir: true\n")
	b.WriteString("  read_only:\n")
	b.WriteString("    - /usr\n")
	b.WriteString("    - /lib\n")
	b.WriteString("    - /proc\n")
	b.WriteString("    - /dev/urandom\n")
	b.WriteString("    - /app\n")
	b.WriteString("    - /etc\n")
	b.WriteString("    - /var/log\n")
	b.WriteString("  read_write:\n")
	b.WriteString("    - /data\n")
	b.WriteString("    - /tmp\n")
	b.WriteString("    - /dev/null\n")
	b.WriteString("\n")
	b.WriteString("landlock:\n")
	b.WriteString("  compatibility: best_effort\n")
	b.WriteString("\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# Process (static - locked at sandbox creation)\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("process:\n")
	b.WriteString("  run_as_user: alice\n")
	b.WriteString("  run_as_group: alice\n")
	b.WriteString("\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("# Network (dynamic - hot-reloadable with `openshell policy set`)\n")
	b.WriteString("# ---------------------------------------------------------------------------\n")
	b.WriteString("network_policies:\n")

	serverHost, serverPort := parseURLForPolicy(strings.TrimSpace(cfg.Server.BaseURL))
	if isLoopbackHost(serverHost) {
		b.WriteString("\n")
		b.WriteString("  # WARNING: The coordination server URL resolves to a loopback address.\n")
		b.WriteString("  # OpenShell always blocks loopback traffic regardless of policy.\n")
		b.WriteString("  # Switch to a routable hostname before applying this policy,\n")
		b.WriteString("  # or test the policy in audit mode first.\n")
	}
	writePolicyBlock(&b, "alice_server", "alice-coordination-server", []openShellEndpoint{{
		host: serverHost,
		port: serverPort,
	}})

	if cfg.GitHubLiveEnabled() {
		host, port := parseURLForPolicy(cfg.GitHubAPIBaseURL())
		writePolicyBlock(&b, "github_api", "github-api", []openShellEndpoint{{
			host: host,
			port: port,
		}})
	}

	if cfg.GitHubOAuthEnabled() {
		oauthCfg := cfg.GitHubOAuthConfig()
		endpoints := uniquePolicyEndpoints(
			openShellEndpointFromURL(oauthCfg.AuthorizationURL),
			openShellEndpointFromURL(oauthCfg.TokenURL),
		)
		writePolicyBlock(&b, "github_oauth", "github-oauth", endpoints)
	}

	if cfg.JiraLiveEnabled() || cfg.JiraOAuthEnabled() {
		endpoints := make([]openShellEndpoint, 0, 3)
		if cfg.JiraLiveEnabled() {
			endpoints = append(endpoints, openShellEndpointFromURL(cfg.JiraAPIBaseURL()))
		}
		if cfg.JiraOAuthEnabled() {
			oauthCfg := cfg.JiraOAuthConfig()
			endpoints = append(endpoints,
				openShellEndpointFromURL(oauthCfg.AuthorizationURL),
				openShellEndpointFromURL(oauthCfg.TokenURL),
			)
		}
		writePolicyBlock(&b, "jira_api", "jira-api", uniquePolicyEndpoints(endpoints...))
	}

	if cfg.GCalLiveEnabled() || cfg.GCalOAuthEnabled() {
		endpoints := make([]openShellEndpoint, 0, 3)
		if cfg.GCalLiveEnabled() {
			endpoints = append(endpoints, openShellEndpointFromURL(cfg.GCalAPIBaseURL()))
		}
		if cfg.GCalOAuthEnabled() {
			oauthCfg := cfg.GCalOAuthConfig()
			endpoints = append(endpoints,
				openShellEndpointFromURL(oauthCfg.AuthorizationURL),
				openShellEndpointFromURL(oauthCfg.TokenURL),
			)
		}
		writePolicyBlock(&b, "google_calendar", "google-calendar-api", uniquePolicyEndpoints(endpoints...))
	}

	b.WriteString("\n")
	b.WriteString("# NOTE: ALICE_TRACK_SUMMARISER is an environment variable, not part of edge-agent\n")
	b.WriteString("# config. If you are testing a future LLM-backed summariser, add the model API\n")
	b.WriteString("# hosts manually or start from deploy/openshell/policies/dev.yaml to observe the\n")
	b.WriteString("# required egress before tightening the policy.\n")

	return b.String()
}

func openShellEndpointFromURL(rawURL string) openShellEndpoint {
	host, port := parseURLForPolicy(rawURL)
	return openShellEndpoint{host: host, port: port}
}

func uniquePolicyEndpoints(endpoints ...openShellEndpoint) []openShellEndpoint {
	seen := make(map[string]struct{}, len(endpoints))
	out := make([]openShellEndpoint, 0, len(endpoints))
	for _, endpoint := range endpoints {
		if strings.TrimSpace(endpoint.host) == "" {
			continue
		}
		key := endpoint.host + ":" + strconv.Itoa(endpoint.port)
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		out = append(out, endpoint)
	}
	return out
}

// parseURLForPolicy extracts the host and port from a URL string for use in an
// OpenShell policy endpoint block. HTTPS URLs default to port 443; HTTP URLs
// default to port 80. If rawURL is empty or cannot be parsed, ("", 443) is
// returned.
func parseURLForPolicy(rawURL string) (host string, port int) {
	rawURL = strings.TrimSpace(rawURL)
	if rawURL == "" {
		return "", 443
	}

	if host, port, ok := parsedPolicyURL(rawURL); ok {
		return host, port
	}
	if !strings.Contains(rawURL, "://") {
		if host, port, ok := parsedPolicyURL("https://" + rawURL); ok {
			return host, port
		}
	}

	return "", 443
}

func parsedPolicyURL(rawURL string) (host string, port int, ok bool) {
	u, err := url.Parse(rawURL)
	if err != nil || strings.TrimSpace(u.Host) == "" {
		return "", 0, false
	}

	host = strings.TrimSpace(u.Hostname())
	if host == "" {
		return "", 0, false
	}

	defaultPort := 443
	if strings.EqualFold(u.Scheme, "http") {
		defaultPort = 80
	}
	if strings.TrimSpace(u.Port()) == "" {
		return host, defaultPort, true
	}

	port, err = strconv.Atoi(u.Port())
	if err != nil {
		return host, defaultPort, true
	}
	return host, port, true
}

func writeEndpoint(b *strings.Builder, host string, port int) {
	fmt.Fprintf(b, "      - host: %s\n", host)
	fmt.Fprintf(b, "        port: %d\n", port)
	fmt.Fprintf(b, "        protocol: rest\n")
	fmt.Fprintf(b, "        enforcement: enforce\n")
	fmt.Fprintf(b, "        access: read-write\n")
}

func writePolicyBlock(b *strings.Builder, key string, name string, endpoints []openShellEndpoint) {
	if len(endpoints) == 0 {
		return
	}

	fmt.Fprintf(b, "\n  %s:\n", key)
	fmt.Fprintf(b, "    name: %s\n", name)
	b.WriteString("    endpoints:\n")
	for _, endpoint := range endpoints {
		writeEndpoint(b, endpoint.host, endpoint.port)
	}
	b.WriteString("    binaries:\n")
	fmt.Fprintf(b, "      - path: %s\n", openShellBinaryPath)
}
